BEGIN;
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (1,'Citizen Kane', 1941, '8.3', 119,'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (2, 'Gone with the Wind', 1939, '8.2', 221,'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (3, 'The Godfather', 1972, '9.2', 175, 'Crime');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (4, 'Casablanca', 1942, '8.5', 102, 'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (5, 'Psycho', 1960, '8.5', 109, 'Horror');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (6, 'Lawrence of Arabia', 1962, '8.3', 210, 'Adventure');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (7, 'The Shawshank Redemption', 1994, '9.3', 142,'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (8, 'Star Wars: Episode IV - A New Hope', 1977, '8.6', 121, 'Action' );
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (9, 'The Wizard of Oz', 1939, '8.0', 101, 'Adventure');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (10, 'The Godfather: Part II', 1974, '9.0', 202, 'Crime'); 
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (11, 'Pulp fiction', 1994, '8.9', 154, 'Crime');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (12, 'Schindler s List', 1993, '8.9', 195, 'Action' );
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (13, 'Seven Samurai', 1954, '8.6', 207, 'Action');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (14, 'The Dark Knight', 2008, '9.0', 152, 'Action');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (15, 'Goodfellas', 1990, '8.7', 146, 'Biography');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (16, 'City Lights', 1931, '8.5', 87, 'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (17, 'Apocalypse Now', 1979, '8.4', 153, 'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (18, 'The Matrix', 1999, '8.7', 136, 'Sci-fi');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (19, 'The Great Dictator', 1940, '8.4', 125, 'Comedy');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (20, 'Rear Window', 1954, '8.4', 112, 'Mystery' );
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (21, 'One flew ove the Cuckoo s Nest', 1975, '8.7', 135 , 'Crime');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (22, 'The Silence of the Lambs', 1991, '8.6', 118, 'Thriller');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (23, 'Taxi Driver', 1976, '8.3', 114, 'Crime');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (24, '2001: A Space Odyssey', 1968, '8.3', 143, 'Sci-fi');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (25, 'The Shining', 1980, '8.4', 119, 'Horror' );
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (26, 'The Graduate', 1967, '8.0', 106, 'Romance');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (27, 'It s a Wonderful Life', 1946, '8.6', 131, 'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (28, 'E.T. the Extra-Terrestrial', 1982, '7.8', 114, 'Sci-fi');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (29, 'Back to the Future', 1985, '8.5', 116, 'Sci-fi' );
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (30, 'The Lion King', 1994, '8.5', 88, 'Animation');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (31, 'Fight Club', 1999, '8.8', 139, 'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (32, 'The Good, the Bad and the Ugly', 1966, '8.8', 177, 'Western');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (33, 'Inception',  2010, '8.8', 148, 'Action');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (34, 'The Lord of the Rings: The Fellowship of the Ring', 2001, '8.8', 178, 'Fantasy');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (35, 'Forrest Gump', 1994, '8.8', 142, 'Drama');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (36, 'The Sound of Music', 1965, '8.0', 174, 'Biography');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (37, 'The Pianist', 2002, '8.5', 150, 'Biography');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (38, 'The Green Mile', 1999, '8.6', 189, 'Crime');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (39, 'Apocalypse Now Redux', 2001, '8.4', 202, 'War');
INSERT INTO tblfilms ( filmID, Title, yearReleased, rating, duration, genre) VALUES (40, 'Saving Private Ryan', 1998, '8.6', 170, 'War');
COMMIT;


